version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: email-editor-backend
    ports:
      - "5001:5000"
    volumes:
      - ./emailtemplates:/app/emailtemplates
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: email-editor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
